"Resource/UI/Scoreboard.res"
{
    "scores"
    {
        "ControlName"                   "CTFClientScoreBoardDialog"
        "fieldName"                     "scores"
        "xpos"                          "cs-0.5"
        "ypos"                          "cs-0.5"
        "wide"                          "500"
        "tall"                          "400"
        "medal_width"                   "20"
        "avatar_width"                  "55"
        "spacer"                        "0"
        "name_width"                    "120"
        "nemesis_width"                 "16"
        "class_width"                   "16"
        "score_width"                   "30"
        "ping_width"                    "20"
        "killstreak_width"              "15"
        "killstreak_image_width"        "15"
    }
    "MainBG"
    {
        "ControlName"               "EditablePanel"
        "fieldName"                 "MainBG"
        "ypos"                      "35"
        "zpos"                      "1"
        "wide"                      "500"
        "tall"                      "365"
        "bgcolor_override"          "0 0 0 30"
        "paintBackground"           "1"
        "border"                    ""
    }
    "BlueScoreBG"
    {
        "ControlName"               "CTFImagePanel"
        "fieldName"                 "BlueScoreBG"
        "xpos"                      "0"	// leave it!
        "ypos"                      "0"	// leave it!
        "wide"                      "250"
        "tall"                      "35"
        "image"                     "../hud/color_panel_blu"
        "src_corner_height"         "23"
        "src_corner_width"          "23"
        "draw_corner_height"        "0"
        "draw_corner_width"         "0"
    }
    "BlueTeamImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "BlueTeamImage"
        "xpos"                  "5"
        "ypos"                  "3"
        "zpos"                  "1"
        "wide"                  "30"
        "tall"                  "30"
        "image"                 "../hud/team_blue"
        "scaleImage"            "1"
    }
    "BlueTeamLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "BlueTeamLabel"
        "font"                  "CenterPrintText"
        "labelText"             "%blueteamname%"
        "textAlignment"         "west"
        "xpos"                  "40"
        "xpos_minmode"          "390"
        "ypos"                  "2"
        "zpos"                  "20"
        "wide"                  "150"
        "tall"                  "30"
        "fgcolor"               "white"
    }
    "BlueTeamPlayerCount"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "BlueTeamPlayerCount"
        "font"                  "CenterPrintText"
        "labelText"             "%blueteamplayercount%"
        "textAlignment"         "center"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "0"
        "wide"                  "250"
        "tall"                  "35"
        "fgcolor"               "White"
    }
    "BlueTeamScore"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "BlueTeamScore"
        "font"                  "ScoreboardTeamScoreNew"
        "labelText"             "%blueteamscore%"
        "textAlignment"         "east"
        "xpos"                  "140"
        "ypos"                  "-1"
        "zpos"                  "4"
        "wide"                  "100"
        "tall"                  "35"
        "fgcolor"               "White"
    }
    "BlueTeamScoreDropshadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "BlueTeamScoreDropshadow"
        "font"                  "ScoreboardTeamScoreNew"
        "labelText"             "%blueteamscore%"
        "textAlignment"         "east"
        "xpos"                  "142"
        "ypos"                  "1"
        "zpos"                  "3"
        "wide"                  "100"
        "tall"                  "35"
        "fgcolor"               "0 0 0 255"
    }
    "BluePlayerList"
    {
        "ControlName"           "SectionedListPanel"
        "fieldName"             "BluePlayerList"
        "xpos"                  "0"
        "ypos"                  "35"
        "zpos"                  "20"
        "wide"                  "250"
        "tall"                  "247"
        "linespacing"           "18"
        "linegap"               "2"
        "fgcolor"               "blue"
        "ScrollBar"
        {
            "ControlName"           "Scrollbar"
            "FieldName"             "ScrollBar"
            "tall"                  "0"
            "wide"                  "0"
            "nobuttons"             "1"
            "Slider"
            {
            }
            "UpButton"
            {
                "ControlName"           "Button"
                "FieldName"             "UpButton"
                "visible"               "0"
            }
            "DownButton"
            {
                "ControlName"           "Button"
                "FieldName"             "DownButton"
                "visible"               "0"
            }
        }
    }
    ///
    "RedScoreBG"
    {
        "ControlName"               "CTFImagePanel"
        "fieldName"                 "RedScoreBG"
        "xpos"                      "250"
        "ypos"                      "0"	// leave it!
        "wide"                      "250"
        "tall"                      "35"
        "image"                     "../hud/color_panel_red"
        "src_corner_height"         "23"
        "src_corner_width"          "23"
        "draw_corner_height"        "0"
        "draw_corner_width"         "0"
    }
    "RedTeamImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "RedTeamImage"
        "xpos"                  "457"
        "ypos"                  "-6"
        "zpos"                  "20"
        "wide"                  "47"
        "tall"                  "47"
        "image"                 "../hud/team_red"
        "scaleImage"            "1"
    }
    "RedTeamLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "RedTeamLabel"
        "font"                  "CenterPrintText"
        "labelText"             "%redteamname%"
        "textAlignment"         "east"
        "xpos"                  "310"
        "ypos"                  "2"
        "zpos"                  "20"
        "wide"                  "150"
        "tall"                  "30"
        "fgcolor"               "white"
    }
    "RedTeamPlayerCount"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "RedTeamPlayerCount"
        "font"                  "CenterPrintText"
        "labelText"             "%redteamplayercount%"
        "textAlignment"         "center"
        "xpos"                  "250"
        "ypos"                  "0"
        "zpos"                  "0"
        "wide"                  "250"
        "tall"                  "35"
        "fgcolor"               "White"
    }
    "RedTeamScore"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "RedTeamScore"
        "font"                  "ScoreboardTeamScoreNew"
        "labelText"             "%redteamscore%"
        "textAlignment"         "west"
        "xpos"                  "260"
        "ypos"                  "-1"
        "zpos"                  "4"
        "wide"                  "100"
        "tall"                  "35"
        "fgcolor"               "White"
    }
    "RedTeamScoreDropshadow"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "RedTeamScoreDropshadow"
        "font"                  "ScoreboardTeamScoreNew"
        "labelText"             "%redteamscore%"
        "textAlignment"         "west"
        "xpos"                  "262"
        "ypos"                  "1"
        "zpos"                  "3"
        "wide"                  "100"
        "tall"                  "35"
        "fgcolor"               "0 0 0 255"
    }
    "RedPlayerList"
    {
        "ControlName"           "SectionedListPanel"
        "fieldName"             "RedPlayerList"
        "xpos"                  "250"
        "ypos"                  "35"
        "zpos"                  "20"
        "wide"                  "250"
        "tall"                  "247"
        "linespacing"           "18"
        "linegap"               "2"
        "fgcolor"               "red"
    }
    ///
    "ServerInfoBG"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "ServerInfoBG"
        "xpos"                  "0"
        "ypos"                  "282"
        "wide"                  "500"
        "tall"                  "48"
        "fillcolor"             "0 0 0 70"
    }
    "ServerLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ServerLabel"
        "font"                  "FontCartPrice"
        "labelText"             "%server%"
        "textAlignment"         "west"
        "xpos"                  "5"
        "ypos"                  "280"
        "zpos"                  "3"
        "wide"                  "380"
        "tall"                  "25"
        "visible"               "1"
    }
    "ServerLabelNew"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ServerLabel"
        "font"                  "FontCartPrice"
        "labelText"             "%server%"
        "textAlignment"         "west"
        "xpos"                  "5"
        "ypos"                  "280"
        "wide"                  "380"
        "tall"                  "25"
    }
    "ServerTimeLeftLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ServerTimeLeftLabel"
        "font"                  "ScoreboardVerySmall"
        "labelText"             "#Scoreboard_TimeLeftLabel"
        "textAlignment"         "center"
        "xpos"                  "385"
        "ypos"                  "287"
        "zpos"                  "2"
        "wide"                  "72"
        "tall"                  "10"
    }
    "ServerTimeLeftValue"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ServerTimeLeftValue"
        "font"                  "ScoreboardMediumSmall"
        "labelText"             "%servertime%"
        "textAlignment"         "east"
        "xpos"                  "435"
        "ypos"                  "282"
        "zpos"                  "2"
        "wide"                  "72"
        "tall"                  "20"
        "fgcolor"               "White"
        "centerwrap"            "1"
    }
    "Spectators"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "Spectators"
        "font"                  "ScoreboardVerySmall"
        "labelText"             "%spectators%"
        "textAlignment"         "west"
        "xpos"                  "5"
        "ypos"                  "296"
        "zpos"                  "4"
        "wide"                  "424"
        "tall"                  "20"
    }
    "SpectatorsInQueue"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "SpectatorsInQueue"
        "font"                  "ScoreboardVerySmall"
        "labelText"             "%waitingtoplay%"
        "textAlignment"         "east"
        "xpos"                  "r424"
        "ypos"                  "296"
        "zpos"                  "4"
        "wide"                  "424"
        "tall"                  "20"
    }
    "PlayerNameLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "PlayerNameLabel"
        "font"                  "EconFontSmall"
        "labelText"             "%playername%"
        "textAlignment"         "west"
        "xpos"                  "5"
        "ypos"                  "311"
        "zpos"                  "3"
        "wide"                  "300"
        "tall"                  "20"
    }
    "PlayerNameLabelShadow"
    {
        "ControlName"                   "CExLabel"
        "fieldName"                     "PlayerNameLabelShadow"
        "font"                          "EconFontSmall"
        "labelText"                     "%playername%"
        "fgcolor"                       "0 0 0 255"
        "textAlignment"                 "west"
        "xpos"                          "-1"
        "ypos"                          "-1"
        "zpos"                          "1"
        "wide"                          "300"
        "tall"                          "20"
        "pin_to_sibling"                "PlayerNameLabel"
        "pin_to_sibling_corner"         "PIN_TOPLEFT"
        "pin_corner_to_sibling"         "PIN_TOPLEFT"
    }
    "MapName"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "mapname"
        "font"                  "GoalText"
        "labelText"             "%mapname%"
        "textAlignment"         "east"
        "xpos"                  "230"
        "ypos"                  "315"
        "zpos"                  "3"
        "wide"                  "265"
        "tall"                  "12"
        "fgcolor"               "White"
    }
    ///
    "StatsBG"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "StatsBG"
        "xpos"                  "0"
        "ypos"                  "332"
        "wide"                  "500"
        "tall"                  "68"
        "fillcolor"             "0 0 0 70"
    }
    "LocalPlayerStatsPanel"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "LocalPlayerStatsPanel"
        "xpos"                  "0"
        "ypos"                  "332"
        "wide"                  "500"
        "tall"                  "70"
        "Kills"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Kills"
            "font"                  "HudFontMediumBig"
            "labelText"             "%kills%"
            "textAlignment"         "east"
            "xpos"                  "-15"
            "ypos"                  "-9"
            "wide"                  "100"
            "tall"                  "50"
            "visible"               "0"
        }
        "KillsNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "KillsNew"
            "font"                          "HudFontMediumBig"
            "labelText"                     "%kills%"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "5"
            "wide"                          "100"
            "tall"                          "50"
            "fgcolor"                       "71 175 122 255"
            "pin_to_sibling"                "Kills"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "KillsNewShadow"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "KillsNewShadow"
            "font"                          "HudFontMediumBig"
            "labelText"                     "%kills%"
            "textAlignment"                 "center"
            "xpos"                          "-2"
            "ypos"                          "-1"
            "zpos"                          "4"
            "wide"                          "100"
            "tall"                          "50"
            "fgcolor"                       "0 0 0 255"
            "pin_to_sibling"                "Kills"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "KillsLabel"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "KillsLabel"
            "font"                          "FontStorePrice"
            "labelText"                     "#TF_Scoreboard_KillsLabel"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "-35"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "20"
            "visible"                       "0"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Kills"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "KillsLabelNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "KillsLabelNew"
            "font"                          "FontStorePrice"
            "labelText"                     "Kills"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "-35"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Kills"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "Assists"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Assists"
            "font"                  "HudFontMediumBig"
            "labelText"             "%assists%"
            "textAlignment"         "center"
            "xpos"                  "35"
            "ypos"                  "-9"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "50"
            "visible"               "0"
        }
        "AssistsNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "AssistsNew"
            "font"                          "HudFontMediumBig"
            "labelText"                     "%assists%"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "5"
            "wide"                          "100"
            "tall"                          "50"
            "fgcolor"                       "252 223 106 255"
            "pin_to_sibling"                "Assists"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "AssistsNewShadow"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "AssistsNewShadow"
            "font"                          "HudFontMediumBig"
            "labelText"                     "%assists%"
            "textAlignment"                 "center"
            "xpos"                          "-2"
            "ypos"                          "-1"
            "zpos"                          "4"
            "wide"                          "100"
            "tall"                          "50"
            "fgcolor"                       "0 0 0 255"
            "pin_to_sibling"                "Assists"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "AssistsLabel"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "AssistsLabel"
            "font"                          "FontStorePrice"
            "labelText"                     "#TF_ScoreBoard_AssistsLabel"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "20"
            "visible"                       "0"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Assists"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "AssistsLabelNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "AssistsLabelNew"
            "font"                          "FontStorePrice"
            "labelText"                     "Assists"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "-35"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Assists"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "Deaths"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Deaths"
            "font"                  "HudFontMediumBig"
            "labelText"             "%deaths%"
            "textAlignment"         "center"
            "xpos"                  "85"
            "ypos"                  "-9"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "50"
            "visible"               "0"
        }
        "DeathsNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DeathsNew"
            "font"                          "HudFontMediumBig"
            "labelText"                     "%deaths%"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "50"
            "fgcolor"                       "224 83 85 255"
            "pin_to_sibling"                "Deaths"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "DeathsNewShadow"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DeathsNewShadow"
            "font"                          "HudFontMediumBig"
            "labelText"                     "%deaths%"
            "textAlignment"                 "center"
            "xpos"                          "-2"
            "ypos"                          "-1"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "50"
            "fgcolor"                       "0 0 0 255"
            "pin_to_sibling"                "Deaths"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "DeathsLabel"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DeathsLabel"
            "font"                          "FontStorePrice"
            "labelText"                     "#TF_ScoreBoard_DeathsLabel"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "-35"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "20"
            "visible"                       "0"
            "pin_to_sibling"                "Deaths"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "DeathsLabelNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DeathsLabelNew"
            "font"                          "FontStorePrice"
            "labelText"                     "Deaths"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "-35"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Deaths"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "Damage"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Damage"
            "font"                  "HudFontMediumSmallSecondary"
            "labelText"             "%damage%"
            "textAlignment"         "center"
            "xpos"                  "35"
            "ypos"                  "38"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "25"
            "visible"               "0"
        }
        "DamageNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DamageNew"
            "font"                          "HudFontMediumSmallSecondary"
            "labelText"                     "%damage%"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "25"
            "fgcolor"                       "85 153 208 255"
            "pin_to_sibling"                "Damage"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "DamageNewShadow"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DamageNewShadow"
            "font"                          "HudFontMediumSmallSecondary"
            "labelText"                     "%damage%"
            "textAlignment"                 "center"
            "xpos"                          "-1"
            "ypos"                          "-1"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "25"
            "fgcolor"                       "0 0 0 255"
            "pin_to_sibling"                "Damage"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "DamageLabel"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DamageLabel"
            "font"                          "FontStorePrice"
            "labelText"                     "#TF_Scoreboard_Damage"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "20"
            "visible"                       "0"
            "pin_to_sibling"                "Damage"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        "DamageLabelNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DamageLabelNew"
            "font"                          "FontStorePrice"
            "labelText"                     "Damage"
            "textAlignment"                 "center"
            "xpos"                          "0"
            "ypos"                          "-15"
            "zpos"                          "3"
            "wide"                          "100"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Damage"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "CapturesLabel"
        {
            "ControlName"               "CExLabel"
            "fieldName"                 "CapturesLabel"
            "font"                      "FontStorePrice"
            "labelText"                 "#TF_ScoreBoard_CapturesLabel"
            "labelText_minmode"         "#TF_ScoreBoard_InvulnLabel"
            "textAlignment"             "east"
            "xpos"                      "150"
            "ypos"                      "2"
            "zpos"                      "3"
            "wide"                      "100"
            "tall"                      "20"
            "fgcolor"                   "White"
        }
        "Captures"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Captures"
            "font"                  "FontStorePrice"
            "labelText"             "%captures%"
            "textAlignment"         "west"
            "xpos"                  "255"
            "ypos"                  "2"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "CapturesNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "CapturesNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%captures%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Captures"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "DefensesLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "DefensesLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_DefensesLabel"
            "textAlignment"         "east"
            "xpos"                  "150"
            "ypos"                  "17"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Defenses"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Defenses"
            "font"                  "FontStorePrice"
            "labelText"             "%defenses%"
            "textAlignment"         "west"
            "xpos"                  "255"
            "ypos"                  "17"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "DefensesNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DefensesNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%defenses%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Defenses"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "DominationLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "DominationLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_DominationLabel"
            "textAlignment"         "east"
            "xpos"                  "150"
            "ypos"                  "32"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Domination"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Domination"
            "font"                  "FontStorePrice"
            "labelText"             "%dominations%"
            "textAlignment"         "west"
            "xpos"                  "255"
            "ypos"                  "32"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "DominationNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DominationNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%dominations%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Domination"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "RevengeLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "RevengeLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_RevengeLabel"
            "textAlignment"         "east"
            "xpos"                  "150"
            "ypos"                  "47"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Revenge"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Revenge"
            "font"                  "FontStorePrice"
            "labelText"             "%Revenge%"
            "textAlignment"         "west"
            "xpos"                  "255"
            "ypos"                  "47"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "RevengeNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "RevengeNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%Revenge%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Revenge"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "HealingLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "HealingLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_HealingLabel"
            "textAlignment"         "east"
            "xpos"                  "260"
            "ypos"                  "2"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Healing"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Healing"
            "font"                  "FontStorePrice"
            "labelText"             "%healing%"
            "textAlignment"         "west"
            "xpos"                  "365"
            "ypos"                  "2"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "HealingNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "HealingNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%healing%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Healing"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "InvulnLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "InvulnLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_InvulnLabel"
            "textAlignment"         "east"
            "xpos"                  "260"
            "ypos"                  "17"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Invuln"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Invuln"
            "font"                  "FontStorePrice"
            "labelText"             "%invulns%"
            "textAlignment"         "west"
            "xpos"                  "365"
            "ypos"                  "17"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "InvulnNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "InvulnNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%invulns%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Invuln"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "TeleportsLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "TeleportsLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_TeleportsLabel"
            "textAlignment"         "east"
            "xpos"                  "260"
            "ypos"                  "32"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Teleports"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Teleports"
            "font"                  "FontStorePrice"
            "labelText"             "%teleports%"
            "textAlignment"         "west"
            "xpos"                  "365"
            "ypos"                  "32"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "TeleportsNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "TeleportsNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%teleports%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Teleports"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "HeadshotsLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "HeadshotsLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_HeadshotsLabel"
            "textAlignment"         "east"
            "xpos"                  "260"
            "ypos"                  "47"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Headshots"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Headshots"
            "font"                  "FontStorePrice"
            "labelText"             "%headshots%"
            "textAlignment"         "west"
            "xpos"                  "365"
            "ypos"                  "47"
            "zpos"                  "3"
            "wide"                  "35"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "HeadshotsNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "HeadshotsNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%headshots%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "35"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Headshots"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "BackstabsLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "BackstabsLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_BackstabsLabel"
            "textAlignment"         "east"
            "xpos"                  "370"
            "ypos"                  "2"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Backstabs"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Backstabs"
            "font"                  "FontStorePrice"
            "labelText"             "%backstabs%"
            "textAlignment"         "west"
            "xpos"                  "475"
            "ypos"                  "2"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "visible"               "0"
        }
        "BackstabsNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "BackstabsNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%backstabs%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Backstabs"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "BonusLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "BonusLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_BonusLabel"
            "textAlignment"         "east"
            "xpos"                  "370"
            "ypos"                  "17"
            "zpos"                  "3"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Bonus"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Bonus"
            "font"                  "FontStorePrice"
            "labelText"             "%bonus%"
            "textAlignment"         "west"
            "xpos"                  "475"
            "ypos"                  "17"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "BonusNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "BonusNew"
            "labelText"                     "%bonus%"
            "font"                          "FontStorePrice"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Bonus"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "SupportLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "SupportLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_Scoreboard_Support"
            "textAlignment"         "east"
            "xpos"                  "370"
            "ypos"                  "32"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Support"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Support"
            "font"                  "FontStorePrice"
            "labelText"             "%support%"
            "textAlignment"         "west"
            "xpos"                  "475"
            "ypos"                  "32"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "SupportNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "SupportNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%support%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Support"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "DestructionLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "DestructionLabel"
            "font"                  "FontStorePrice"
            "labelText"             "#TF_ScoreBoard_DestructionLabel"
            "textAlignment"         "east"
            "xpos"                  "370"
            "ypos"                  "47"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "fgcolor"               "White"
        }
        "Destruction"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "Destruction"
            "font"                  "FontStorePrice"
            "labelText"             "%destruction%"
            "textAlignment"         "west"
            "xpos"                  "475"
            "ypos"                  "47"
            "zpos"                  "3"
            "wide"                  "40"
            "tall"                  "20"
            "fgcolor"               "White"
            "visible"               "0"
        }
        "DestructionNew"
        {
            "ControlName"                   "CExLabel"
            "fieldName"                     "DestructionNew"
            "font"                          "FontStorePrice"
            "labelText"                     "%destruction%"
            "textAlignment"                 "west"
            "xpos"                          "0"
            "ypos"                          "0"
            "zpos"                          "4"
            "wide"                          "40"
            "tall"                          "20"
            "fgcolor"                       "White"
            "pin_to_sibling"                "Destruction"
            "pin_to_sibling_corner"         "PIN_TOPLEFT"
            "pin_corner_to_sibling"         "PIN_TOPLEFT"
        }
        ///
        "GameType"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "gametype"
            "font"                  "ScoreboardVerySmall"
            "labelText"             "%gametype%"
            "textAlignment"         "east"
            "xpos"                  "435"
            "ypos"                  "32"
            "zpos"                  "3"
            "wide"                  "145"
            "tall"                  "20"
            "fgcolor"               "185 177 153 255"
        }
    }
    /// 
    "MvMScoreboard"
    {
        "ControlName"           "CTFHudMannVsMachineScoreboard"
        "fieldName"             "MvMScoreboard"
        "xpos"                  "0"
        "ypos"                  "0"
        "zpos"                  "10"
        "wide"                  "f0"
        "tall"                  "f0"
        "visible"               "0"
        "enabled"               "1"
        "verbose"               "1"
        "if_mvm"
        {
            "visible"           "1"
        }
    }
    "LocalPlayerDuelStatsPanel"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "LocalPlayerDuelStatsPanel"
        "xpos"                  "0"
        "ypos"                  "395"
        "zpos"                  "3"
        "wide"                  "600"
        "tall"                  "53"
        "autoResize"            "0"
        "pinCorner"             "0"
        "visible"               "1"
        "enabled"               "1"
        "if_mvm"
        {
            "visible"           "0"
        }
        "DuelingLabel"
        {
            "ControlName"           "CExLabel"
            "fieldName"             "DuelingLabel"
            "font"                  "ScoreboardSmall"
            "labelText"             "#TF_ScoreBoard_Dueling"
            "textAlignment"         "center"
            "xpos"                  "250"
            "ypos"                  "2	"
            "zpos"                  "3"
            "wide"                  "100"
            "tall"                  "20"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
        }
        "DuelingIcon"
        {
            "ControlName"           "ImagePanel"
            "fieldName"             "DuelingIcon"
            "xpos"                  "284"
            "ypos"                  "15"
            "zpos"                  "2"
            "wide"                  "32"
            "tall"                  "32"
            "visible"               "1"
            "enabled"               "1"
            "image"                 "../backpack/player/items/crafting/icon_dueling"
            "scaleImage"            "1"
        }
        "LocalPlayerData"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "LocalPlayerData"
            "xpos"                  "75"
            "ypos"                  "0"
            "wide"                  "200"
            "tall"                  "53"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "AvatarBGPanel"
            {
                "ControlName"                   "EditablePanel"
                "fieldName"                     "AvatarBGPanel"
                "xpos"                          "157"
                "ypos"                          "7"
                "zpos"                          "-1"
                "wide"                          "36"
                "tall"                          "36"
                "visible"                       "1"
                "PaintBackgroundType"           "2"
                "bgcolor_override"              "117 107 94 255"
            }
            "AvatarImage"
            {
                "ControlName"           "CAvatarImagePanel"
                "fieldName"             "AvatarImage"
                "xpos"                  "159"
                "ypos"                  "9"
                "zpos"                  "0"
                "wide"                  "32"
                "tall"                  "32"
                "visible"               "1"
                "enabled"               "1"
                "image"                 ""
                "scaleImage"            "1"
                "color_outline"         "52 48 45 255"
            }
            "AvatarTextLabel"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "AvatarTextLabel"
                "fgcolor"               "TanLight"
                "xpos"                  "50"
                "ypos"                  "7"
                "zpos"                  "2"
                "wide"                  "100"
                "tall"                  "18"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "wrap"                  "0"
                "labelText"             "%playername%"
                "textAlignment"         "east"
                "font"                  "HudFontSmallest"
            }
            "Score"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "Score"
                "labelText"             "%score%"
                "textAlignment"         "east"
                "xpos"                  "50"
                "ypos"                  "23"
                "zpos"                  "3"
                "wide"                  "100"
                "tall"                  "20"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "font"                  "ScoreboardMedium"
            }
        }
        "OpponentData"
        {
            "ControlName"           "EditablePanel"
            "fieldName"             "OpponentData"
            "xpos"                  "325"
            "ypos"                  "0"
            "wide"                  "200"
            "tall"                  "53"
            "autoResize"            "0"
            "pinCorner"             "0"
            "visible"               "1"
            "enabled"               "1"
            "AvatarBGPanel"
            {
                "ControlName"                   "EditablePanel"
                "fieldName"                     "AvatarBGPanel"
                "xpos"                          "7"
                "ypos"                          "7"
                "zpos"                          "-1"
                "wide"                          "36"
                "tall"                          "36"
                "visible"                       "1"
                "PaintBackgroundType"           "2"
                "bgcolor_override"              "117 107 94 255"
            }
            "AvatarImage"
            {
                "ControlName"           "CAvatarImagePanel"
                "fieldName"             "AvatarImage"
                "xpos"                  "9"
                "ypos"                  "9"
                "zpos"                  "0"
                "wide"                  "32"
                "tall"                  "32"
                "visible"               "1"
                "enabled"               "1"
                "image"                 ""
                "scaleImage"            "1"
                "color_outline"         "52 48 45 255"
            }
            "AvatarTextLabel"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "AvatarTextLabel"
                "fgcolor"               "TanLight"
                "xpos"                  "50"
                "ypos"                  "7"
                "zpos"                  "2"
                "wide"                  "100"
                "tall"                  "18"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "wrap"                  "0"
                "labelText"             "%playername%"
                "textAlignment"         "west"
                "font"                  "HudFontSmallest"
            }
            "Score"
            {
                "ControlName"           "CExLabel"
                "fieldName"             "Score"
                "labelText"             "%score%"
                "textAlignment"         "west"
                "xpos"                  "50"
                "ypos"                  "23"
                "zpos"                  "3"
                "wide"                  "200"
                "tall"                  "20"
                "autoResize"            "0"
                "pinCorner"             "0"
                "visible"               "1"
                "enabled"               "1"
                "font"                  "ScoreboardMedium"
            }
        }
    }
    /// IM DONT KNOW THIS DOES
    "PlayerScoreLabel"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "PlayerScoreLabel"
        "font"                  "ScoreboardMedium"
        "labelText"             "%playerscore%"
        "textAlignment"         "east"
        "xpos"                  "150"
        "ypos"                  "377"
        "zpos"                  "3"
        "wide"                  "140"
        "tall"                  "20"
    }
    /// DEFINED TO DISABLE
    "TimerBG"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "TimerBG"
        "wide"                  "0"
        "tall"                  "0"
    }
    "ServerTimeLeft"
    {
        "ControlName"           "CExLabel"
        "fieldName"             "ServerTimeLeft"
        "wide"                  "0"
        "tall"                  "0"
    }
    "ServerTimeLeftInsetBG"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "ServerTimeLeftInsetBG"
        "wide"                  "0"
        "tall"                  "0"
    }
    "BlueLeaderAvatar"
    {
        "ControlName"           "CAvatarImagePanel"
        "fieldName"             "BlueLeaderAvatar"
        "wide"                  "0"
        "tall"                  "0"
    }
    "BlueLeaderAvatarBG"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "BlueLeaderAvatarBG"
        "wide"                  "0"
        "tall"                  "0"
    }
    "RedLeaderAvatar"
    {
        "ControlName"           "CAvatarImagePanel"
        "fieldName"             "RedLeaderAvatar"
        "wide"                  "0"
        "tall"                  "0"
    }
    "RedLeaderAvatarBG"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "RedLeaderAvatarBG"
        "wide"                  "0"
        "tall"                  "0"
    }
    "ClassImage"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "ClassImage"
        "wide"                  "92"
        "tall"                  "92"
    }
    "classmodelpanel"
    {
        "ControlName"           "CTFPlayerModelPanel"
        "fieldName"             "classmodelpanel"
        "wide"                  "0"
        "tall"                  "0"
    }
    "PlayerNameBG"
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "PlayerNameBG"
        "wide"                  "0"
        "tall"                  "0"
    }
    "ShadedBar"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "ShadedBar"
        "wide"                  "0"
        "tall"                  "0"
    }
    "HorizontalLine"
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "HorizontalLine"
        "wide"                  "0"
        "tall"                  "0"
    }
    "VerticalLine"
    {
        "ControlName"                   "ImagePanel"
        "fieldName"                     "VerticalLine"
        "wide"                          "0"
        "tall"                          "0"
    }
    "ButtonLegendBG" [$X360]
    {
        "ControlName"           "ImagePanel"
        "fieldName"             "ButtonLegendBG"
        "wide"                  "0"
        "tall"                  "0"
    }
    "ButtonLegend" [$X360]
    {
        "ControlName"           "EditablePanel"
        "fieldName"             "ButtonLegend"
        "wide"                  "0"
        "tall"                  "0"
    }
}