"Resource/UI/Speedometer.res"
{
	"Speed_Anchor"
	{
		"controlName"				"EditablePanel"
		"fieldName"					"Speed_Anchor"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"Speed_Digit_1"
	{
		"controlName"				"ImagePanel"
		"fieldName"					"Speed_Digit_1"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"Speed_Digit_1_Shadow"
	{
		"controlName"				"ImagePanel"
		"fieldName"					"Speed_Digit_1_Shadow"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"Speed_Digit_2"
	{
		"controlName"				"ImagePanel"
		"fieldName"					"Speed_Digit_2"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"Speed_Digit_2_Shadow"
	{
		"controlName"				"ImagePanel"
		"fieldName"					"Speed_Digit_2_Shadow"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"Speed_Digit_3"
	{
		"controlName"				"ImagePanel"
		"fieldName"					"Speed_Digit_3"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"Speed_Digit_3_Shadow"
	{
		"controlName"				"ImagePanel"
		"fieldName"					"Speed_Digit_3_Shadow"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"Speed_Digit_4"
	{
		"controlName"				"ImagePanel"
		"fieldName"					"Speed_Digit_4"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
	"Speed_Digit_4_Shadow"
	{
		"controlName"				"ImagePanel"
		"fieldName"					"Speed_Digit_4_Shadow"
		"xpos"						"0"
		"ypos"						"0"
		"zpos"						"0"
		"wide"						"0"
		"tall"						"0"
		"visible"					"0"
		"enabled"					"0"
	}
}